### PR TITLE
Migrate scale_sudo -> fb_sudo; fix dd-agent postix sudo access

### LINKED ISSUE #296: Datadog is failing to run commands to gather postfix data
```
Oct 11 18:52:18 scale-lists2 sudo[3737505]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Oct 11 18:52:18 scale-lists2 sudo[3737507]: pam_unix(sudo:auth): conversation failed
Oct 11 18:52:18 scale-lists2 sudo[3737507]: pam_unix(sudo:auth): auth could not identify password for [dd-agent]
Oct 11 18:52:20 scale-lists2 sudo[3737507]: dd-agent : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/find /var/spool/postfix/active -type f
```

### PR DESCRIPTION
**Pull request by jaymzh**
Migrate scale_sudo -> fb_sudo; fix dd-agent postix sudo access

Summary:

* Migrate from `scale_sudo`, our hacky solution before `fb_sudo` was
  opensourced, to `fb_sudo`
* Fix dd-agent's sudo config

Closes #296

Test Plan:

Taste-tested and got...

```
    --- /etc/sudoers	2023-08-23 03:51:04.724300851 +0000
    +++ /tmp/.chef-sudoers20231012-3840474-6rscpw	2023-10-12 01:34:29.864507596 +0000
    @@ -1,14 +1,25 @@
     # This file is managed by Chef

    -Defaults  !visiblepw, always_set_home, env_reset, env_keep="COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY", secure_path = /sbin:/bin:/usr/sbin:/usr/bin
    +Defaults !visiblepw
    +Defaults always_set_home
    +Defaults env_reset
    +Defaults env_keep="COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
    +Defaults secure_path="/sbin:/bin:/usr/sbin:/usr/bin"

    +
     # Host aliases

     # User aliases

    +# User aliases
    +
     # Command aliases

     # Users
    +## all
    +%sudo ALL=(ALL) ALL
    +## admins can run anything
     %sudo ALL=NOPASSWD: ALL
    -dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix/ -type f, /bin/find /var/spool/postfix/ -type f
    +## postfix
    +dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix/incoming -type f
    - Would restore selinux security context
```

plus:
```
Oct 12 01:53:01 scale-lists2 sudo[3846097]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Oct 12 01:53:01 scale-lists2 sudo[3846099]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/find /var/spool/postfix/deferred -type f
Oct 12 01:53:01 scale-lists2 sudo[3846099]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 12 01:53:01 scale-lists2 sudo[3846099]: pam_unix(sudo:session): session closed for user root
Oct 12 01:53:16 scale-lists2 sudo[3846152]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Oct 12 01:53:16 scale-lists2 sudo[3846154]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/find /var/spool/postfix/incoming -type f
Oct 12 01:53:16 scale-lists2 sudo[3846154]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 12 01:53:16 scale-lists2 sudo[3846154]: pam_unix(sudo:session): session closed for user root
Oct 12 01:53:16 scale-lists2 sudo[3846168]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Oct 12 01:53:16 scale-lists2 sudo[3846171]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/find /var/spool/postfix/active -type f
Oct 12 01:53:16 scale-lists2 sudo[3846171]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 12 01:53:16 scale-lists2 sudo[3846171]: pam_unix(sudo:session): session closed for user root
Oct 12 01:53:16 scale-lists2 sudo[3846175]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Oct 12 01:53:16 scale-lists2 sudo[3846177]: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/find /var/spool/postfix/deferred -type f
```

### CODE REVIEW

File: cookbooks/fb_init/recipes/site_settings.rb [hunk 1]
```diff
@@ -61,17 +63,26 @@
...
+    'queues' => queues,
   }],
 }
 
-node.default['scale_sudo']['users']['dd-agent'] =
-  'ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix/ -type f, ' +
-  '/bin/find /var/spool/postfix/ -type f'
+queues.each do |q|
+  # the docs say they use /usr/bin/find, but they seem to use /bin/find
+  # so just allow for both...
```
Comment (davide125) [inline cookbooks/fb_init/recipes/site_settings.rb:77]: Probably a side effect of usrmerge, allowing both is fine

File: cookbooks/fb_init/recipes/site_settings.rb [hunk 2]
```diff
@@ -61,17 +63,26 @@
...
+  node.default['fb_sudo']['users']['dd-agent']["postfix_#{q}"] =
+    "ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix/#{q} -type f," +
+    "/bin/find /var/spool/postfix/#{q} -type f"
+end
+
+puts "PHILD!!!"
+pp node['fb_sudo']['users']
+#node.default['fb_sudo']['defaults']['dd-agent'] = '!requiretty'
```
Comment (davide125) [inline cookbooks/fb_init/recipes/site_settings.rb:85]: debugging leftovers

**Review by davide125 — CHANGES_REQUESTED** [review]

**Review by davide125 — APPROVED** [review]
